export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const UPDATE_LOGIN_STATE = 'UPDATE_LOGIN_STATE';
export const UPDATE_INITIALIZE_STATE = 'UPDATE_INITIALIZE_STATE';
