// book
export const BOOK_UPDATE_BOOK = 'BOOK/BOOK_UPDATE_BOOK';
export const BOOK_UPDATE_CARD = 'BOOK/BOOK_UPDATE_CARD';

// card
export const CARD_ADD_CARDS = 'CARD/CARD_ADD_CARDS';
export const CARD_UPDATE_CARDS = 'CARD/UPDATE_CARDS';
export const CARD_UPDATE_CURRENT_PAGE = 'CARD/UPDATE_CURRENT_PAGE';
export const CARD_UPDATE_FETCHED_PUBLICATION_LIST_TYPE = 'CARD/UPDATE_FETCHED_PUBLICATION_LIST_TYPE';
export const CARD_UPDATE_LIST_TYPE = 'CARD/UPDATE_LIST_TYPE';
export const CARD_UPDATE_SEARCH_PENDING = 'CARD/UPDATE_SEARCH_PENDING';
export const CARD_UPDATE_SEARCH_QUERY = 'CARD/UPDATE_SEARCH_QUERY';
export const CARD_UPDATE_TOTAL_PAGES = 'CARD/UPDATE_TOTAL_PAGES';

// centerLoader
export const CENTER_LOADER_HIDE = 'CENTER_LOADER/HIDE';
export const CENTER_LOADER_SHOW = 'CENTER_LOADER/SHOW';

// error
export const ERROR_UPDATE_GENERAL = 'ERROR/ERROR_UPDATE_GENERAL';
export const ERROR_UPDATE_MODAL = 'ERROR/ERROR_UPDATE_MODAL';

// loader
export const LOADER_CLEAR = 'LOADER/CLEAR';
export const LOADER_HIDE = 'LOADER/HIDE';
export const LOADER_SHOW = 'LOADER/SHOW';

// publication
export const PUBLICATION_UPDATE_CARD = 'PUBLICATION/PUBLICATION_UPDATE_CARD';
export const PUBLICATION_UPDATE_PUBLICATION = 'PUBLICATION/PUBLICATION_UPDATE_PUBLICATION';

// publisher
export const PUBLISHER_UPDATE_CARD = 'PUBLISHER/PUBLISHER_UPDATE_CARD';
export const PUBLISHER_UPDATE_PUBLISHER = 'PUBLISHER/PUBLISHER_UPDATE_PUBLISHER';

// row
export const ROW_UPDATE_ROWS = 'ROW/UPDATE_ROWS';

// screen
export const SCREEN_HIDE_DRAWER = 'SCREEN/HIDE_DRAWER';
export const SCREEN_SHOW_DRAWER = 'SCREEN/SHOW_DRAWER';

// user
export const USER_UPDATE_LOGIN_STATE = 'USER/UPDATE_LOGIN_STATE';
export const USER_UPDATE_INITIALIZE_STATE = 'USER/UPDATE_INITIALIZE_STATE';

// writer
export const WRITER_UPDATE_CARD = 'WRITER/WRITER_UPDATE_CARD';
export const WRITER_UPDATE_WRITER = 'WRITER/WRITER_UPDATE_WRITER';
