// @flow

export const LOADER_DEFAULT = 'LOADER_DEFAULT';
export const LOADER_CARD_LIST = 'LOADER_CARD_LIST';
export const LOADER_LOGIN = 'LOADER_LOGIN';
export const LOADER_LOGOUT = 'LOADER_LOGOUT';
export const LOADER_REGISTER = 'LOADER_REGISTER';
export const LOADER_CARD_DETAIL = 'LOADER_CARD_DETAIL';
export const LOADER_TOGGLE_LIST = 'LOADER_TOGGLE_LIST';
export const LOADER_ADD_LIST = 'LOADER_ADD_LIST';
