// @flow

export const PERMISSIONS = {
  EDIT_PUBLICATION: 'EDIT_PUBLICATION',
  EDIT_BOOK: 'EDIT_BOOK',
  EDIT_WRITER: 'EDIT_WRITER',
  EDIT_PUBLISHER: 'EDIT_PUBLISHER',
  EDIT_USER: 'EDIT_USER',
};
