// @flow

export const CARD_TYPES = {
  PUBLICATION: 'CARD_TYPE_PUBLICATION',
  BOOK: 'CARD_TYPE_BOOK',
  WRITER: 'CARD_TYPE_WRITER',
  PUBLISHER: 'CARD_TYPE_PUBLISHER',
  USER: 'CARD_TYPE_USER',
  ITEM: 'CARD_TYPE_ITEM',
};

export const BASE_CARD_TYPE_BOOK = 'BASE_CARD_TYPE_BOOK';
export const BASE_CARD_TYPE_WRITER = 'BASE_CARD_TYPE_WRITER';
export const BASE_CARD_TYPE_PUBLISHER = 'BASE_CARD_TYPE_PUBLISHER';

export const SUB_ITEM_TYPE_PUBLICATION = 'SUB_ITEM_TYPE_PUBLICATION';
export const SUB_ITEM_TYPE_BOOK = 'SUB_ITEM_TYPE_BOOK';

export const BASE_CARD_DATA_MAP_KEYS = {
  ID: 'id',
  TITLE: 'title',
  TYPE: 'type',
};
